class Integer:
    def __lt__(self, other: object) -> bool: ...

    def __le__(self, other: object) -> bool: ...

    def __eq__(self, other: object) -> bool: ...

    def __ne__(self, other: object) -> bool: ...

    def __gt__(self, other: object) -> bool: ...

    def __ge__(self, other: object) -> bool: ...

    def bit_length(self) -> int: ...

    def __index__(self) -> int: ...
