# Copyright 2026 Google LLC.
# EC test circuits and benchmarks (not used in production)

proofs_add_test(prove_verify_test prove_verify_shared.cc)
target_link_libraries(prove_verify_test flatsha)

proofs_add_test(prove_verify_no_cft_test prove_verify_no_cft_shared.cc)
target_link_libraries(prove_verify_no_cft_test flatsha)

proofs_add_test(attr_commitment_experiment_test attr_commitment_experiment_shared.cc)
target_link_libraries(attr_commitment_experiment_test flatsha)

proofs_add_test(prove_verify_revocation_test prove_verify_revocation_shared.cc)
target_link_libraries(prove_verify_revocation_test flatsha)
