from typing import Self, overload

from sage.rings.finite_rings.finite_field_base import FiniteField
from sage.rings.polynomial.multi_polynomial import MPolynomial


class FiniteRingElement:
    @overload
    def __add__(self, other: Self) -> Self: ...
    @overload
    def __add__(self, other: MPolynomial) -> MPolynomial: ...

    @overload
    def __sub__(self, other: Self) -> Self: ...
    @overload
    def __sub__(self, other: MPolynomial) -> MPolynomial: ...

    @overload
    def __mul__(self, other: Self) -> Self: ...
    @overload
    def __mul__(self, other: MPolynomial) -> MPolynomial: ...

    def __pow__(self, other: int) -> Self: ...

    def __neg__(self) -> Self: ...

    def is_zero(self) -> bool: ...

    # While this is actually defined on SageObject, we want to declare it
    # with different types depending on the child class.
    def parent(self) -> FiniteField: ...

    def to_bytes(self, byteorder: str = "big") -> bytes: ...
